apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-secret
  namespace: default
spec:
  encryptedData:
    MONGODB_URI: AgC+vxYXhaXFhpJsg5+9GoXWTLk3sdATkXje67pOaxobqpvJd7C6V+sJvdlv8EWIQvHJMMn3d7lO9KuyevSTrjn/9qEGaAom80GEgB7Uo387fkKLffHPm4cK7jwCq+WwUxqhRjvfm2oP9qMMThX6mZrPlJCvZXt9vgtjabb7QcmogZ7ySJSkRxHLSTgao2w8RpZOshaXs5wIcOzXxjD3LwXgKoOpPIylogd8o7cIyb4B0vdYq057rCP5BK0EufmELBPbHnFtoPzKB3vuwLlredESe1iNRdACWARFs06uYViMrSP1cBfyZibP2WA/UmiMj07+50Gx92UviADVtuhbHzwIAKwiM3Ljlw9aetKtDrKPzGm0h46Tqzl1sdClkCuUWHH+xKCeF7VJ7KILq6p+RfTF1wS51Y8BZ4q1jsbQhKZVEVcjc3+HP/FkfyEi8by1GM4Uhob0sk/RIzRrdtggGW45yJAnBNTr7iET2nLngFtOLO4HbnWatG5ayevpoyqmWB5xCpH46JT8rI1D1TzcX6CHezJ1Q6LjjxcnimkdrGvVG6iRIrcxG/3OH6KqjzI9n3eP3LoydDQ9HVAoW8x6EwXDNe7cOIsJZdG+BjEN90hDVZ0MHyuThhdTPT2TVQ+stvsY1ZcPqTrdo1NAEZQ80sybVHLpKMOudbEGSE0EV/55nhEzZnsfoHwJm6Og27LlW/YRVr6fvBQSkbCjwAZOSj9hCDgemIsLiSUMwFR1Cp272DBhscqey2xY6CWdp0hz0Q==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: default
    type: Opaque

