apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-secret
  namespace: default
spec:
  encryptedData:
    MONGODB_URI: AgCY2Xm2vrie9NpJnazSetZuhdAUbKRzgU5tJshEzp2CfBpCH7wNmzX1yyAeps73dQoCgg8jVXmMYgR9c70jZO4Rt73pkwiduRKW6aLCqIbVjz6W2pk7gRvLFhQH6A7FJ0RttGffpO0N89OXDtgUWoSASj7uiBUAzaaw13mJy4EmcJqoWZRmMa2HhplidYbd0xVLXRn49GJYy+OVykUolSUwvlzINOwaDG+xgTvXrugj5MjQxZQJQPllHklkmpZnfoWr0br2AHExMmO+qhOMuZO3koad/x1VrBlQep3PW+PXwfjUGe+NQSxQ3ZO/P5scK6mk2uOQlihkdzo8dgV/XbUQEGlVhz2gWpLpODWERehYC+5oUFXi+2+CDCXi15WhTxRmxY3fyoagJcoQkJKAZbb7ZNvKbW1Y9u0yMXgeknkLxTW17Jzhz3TmdbUUe7bqDofElcNmTyAAGuOFLIFQSV+k6fSwd7KMZSqVPmtwY5kWgAIShvTAP37KSoSTWR4KurKeIfvFftHRir6rsVH6K5TMAO+W+DSv6Rcub/bqeVP2NDohWRBze5VsRaN1OOzH2nxeuDIYT4VZBjZ0XIAhqpMsEUpNc01Zz3wFc8AghfK3J2CMSdXzDlmQmwp2++ujuRo9U7rK0jOW5E902CJNruPa1jJIhLaYHCvG6Rz0OLIEKa7akaS3xiqTBN838jw11Ml14pmL8KZ6jVSFTqsJtWS0IaCcPyiflgdBXcjF5H9qtoQkyVcDc+2mIdx4VAMq0Q==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: default
    type: Opaque

