apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-secret
  namespace: default
spec:
  encryptedData:
    MONGODB_URI: AgCsfGROduirwKIfL/OFYc44CUaz0/OKF6x3RnH8nuaD4oat7lDdPhDoLFNCiF6uakA3WfvRvVMtaPAk1Y8hrCNEZE0ghD2ReMSimfkPFD/xfPGnh6a8cFtBYjyozR5tfJK6XMHP6MeF3UKIDkRJX5dOj1honjMZSjre3GjXeBo6r9h7rX61t03UO8o5Pso2kg/naUy+2pgwxtBSRDSGCz+0Eh+Rh0yz/zsatLtnVC8goio8tonn7OjhrP7eHfhk15gX2WxcthzEiMpqeDiYvS5jkUHDnb3MF+9LRpf0wTgnxHT53NidkPekdlNdRcDjbc/VfHStGxvEsMub1PRpj4sZucfYA7Ece9vwLRA0QqqfTg0K915c9LNYJI19VjURYQsQSeUhJLy+s6EgO6WS9EvtM/wGEDo8RoERsHMyh478bXGdk4lNdyHMvZthnJTC0h6gwSjnbrhR/xqQfBaIMVPkLHDAbxnr6nQ+BxO3pZPnTGJJuZ/n6Jhn86lr/lT8ubakIJQuWg+5GnPDfJLbVln0JK/0R6+7mGDkV8+ifbE/icKywbdC8/Hdd89GknCrgoYKQ8mSSn4GkYJ84j39BjTbOvhq4kuADFrdZTIzTpA4eOS7wSlLqLokPmJO5sZuc+AVmmVi6TF6U5MW5TjsNirJmHida6Hh0Z93YI+0VN+pNCUXZNPRbTg4gxzYc/ajM/RddJYj8GsK0I/xw8p76ybXbESsUoGXDGduDnc6BOHJexw+V4LlPWd0nXD12Ke1iQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: default
    type: Opaque

