apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-secret
  namespace: default
spec:
  encryptedData:
    MONGODB_URI: AgAoVt0CwGLaJQGcv6qAsmvh3IuzoFnkdoQRalzoH5jeUUj8CztzIi+REeK0nyNSXN3Fpa6C5WDp81IVeI8fyvq3NGpaVvwM3vJS3pJo/Bvf1Ezb/uqEPudcN68ifz0cWox5hXBXgoZMGWqwhVTphQsNLuZTo3hwkNBBNi/CQrU5O11UrKfFUlPG+7b+m6xfJu3cbAjWJtsKSKctPeS1P83iSRSHgku3IsvhQ2gTioNdSO01jBXkMcJRWcNLW+L0tems6lfePwGcNEODFnXEIYC8E6quzz4F9g5m+s3f3rzjW3KnjI7CdwlosRCsUSH5Z7qOhep9pYoNNNoVnaufHIkD5pf0ylf83g30yIKURAIaBoqsGfTI4ZQmnA7+cZrLP4XPXjXotzpAdi5U9FV9ds9kxxzFSoVthHbyFSFoBqVb7MmrAb+BGKwKYTAC9O7yRb5OmoloXPqTmZP9c6F7h51AB5Bsul8bKz6oaLCg0wQhGaRR45Tjx8wKdQY9/WDNNFd29W6/Weyz4AwWcxMp3BekzKnyTdmYckUsURn6rXllJizhm8t37WF5jtnXZCY3b1SG8kXOuPE0JBX46e0hr1qkGydI3ne8IF9dqOw97nd7NmbR0RrdAuuo3Uh7b2Wr/9/ltNs74HxU+caQ9PmLRjLSGFcit0COw8Wt+yroyd/7Mj2N4bvVztGjhDDBrNbz0HA2JhfTsuLcZPtULCtwjFN8FWPirZX/QwW5Lpv6YM4paikUTfJZyRMXjM/7FbDfdw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: default
    type: Opaque

