apiVersion: v1
kind: Service
metadata:
  name: ingress-prometheus
  namespace: default
spec:
  ports:
  - name: ingress-prometheus
    port: 80
    protocol: TCP
    targetPort: 9113
  selector:
    app: ingress-controller-nginx-ingress
  type: ClusterIP