apiVersion: cert-manager.io/v1
kind: Issuer
metadata: 
  name: letsencrypt-prod
spec: 
  acme: 
    email: piterpiasecki@gmail.com
    preferredChain: ""
    privateKeySecretRef: 
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          route53:
            region: eu-west-3
            hostedZoneID: Z07723113SLTCXLJ17G7M
            accessKeyID: AKIAZMC2XWDGG5MMFEGT
            role: arn:aws:iam::644435390668:role/Piotrek_Role
            secretAccessKeySecretRef:
              name: key
              key: key



    # - http01:
        # ingress:
        #   class: nginx
          # name: app-nginx