apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: key
  namespace: default
spec:
  encryptedData:
    key: AgASY6YuXaVgxv0fcHjFAkQySjCRA3Txl0YBEVTuwMtYF/z623Yve6ND7AYbf5l2vbSHxvvVN90Alfa/mxABJ8gmxwAiWoIC/8iCeo8Yq385hZqvlY/pvcZS6SeA5CwmDsmXEuujcjJKZRYSx5srMEBWqhJB15RpqpwgV+4vAYdx8s4NJmokg7tbGdmgttq+j6WHSznUfAINHtR8ZnY9zqM9+KiJdNlXAI4oeTuaYtkwoLDMYmAtPvYIhswr6YoBcD9t+4KVDI6JtFSUo8Pi2WwMP5D/Syj1gW0kGyrJ4ElZY5J1e2ZA7J8JpGRDgxyoAWJkD112RAnrr0LTVvWn05sjFulVUbtnzt2nAqTaHih/e+mGP7AlFW6awZqWfEUB5O65GNC3XKBsPmDXUYOc+bjGr4xCw0ZV32ikh1SG0p+z6lnaakCHyOmidtBB2pM8DOxJmuvdz6TBimxbVZ/q6I6yX6jCctVWQxazrnHrYpiWJvvQ/7A4YmixDQigpR/OloApgOC+IDFRWjL28q6kNEqErbXN3NwBG3du/DsS7OlmM1toBX6fX4ksMcqYfY5Y6cgvynUTnr9QthvTgjJ5g7N8geDq2lOApF7In7mQCx8iod+MQ2u7M9JQ3INWjQV6FVUTIg1Gd4mQOdoAdZhqIdwuujGnImXozhr8pmG8aRAuE7Axc406w1V5arMwm8BbUCIcjozJc92jGo29rfMiyJoXsiLl43AXgP+dRUnVOZTGM55/rF+RtrsK
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: key
      namespace: default
    type: Opaque

