apiVersion: v1
kind: Service
metadata:
  name: kibana
  annotations:
    external-dns.alpha.kubernetes.io/hostname: kibana.portfolio-pp.click
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-west-3:644435390668:certificate/2f32e1c3-b491-4bea-8847-4510c3a37712
    service.beta.kubernetes.io/aws-load-balancer-ssl-backend-protocol: https
  labels:
    component: kibana
spec:
  type: LoadBalancer
  selector:
    component: kibana
  ports:
  - port: 443
    targetPort: 5601