apiVersion: v1
kind: Service
metadata:
  name: kibana
  external-dns.alpha.kubernetes.io/hostname: kibana.portfolio-pp.click
  labels:
    component: kibana
spec:
  type: LoadBalancer
  selector:
    component: kibana
  ports:
  - port: 80
    targetPort: 5601